org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true


archives_base_name=wandering-traders
maven_group=life.thoms

# Mod Version
mod_version = 1.0.0

# Mod properties
mod_displayname = Wandering Traders
mod_classname = WanderingTraders
mod_description = Discover new wandering traders in Minecraft.\nAlso adds loot recovery (Configurable)
archives_name=wandering-traders
mod_group = life.thoms
mod_id = wandering_traders
mod_license = LGPL-3.0
mod_logo = assets/wandering_traders/logo.png
mod_authors = ThomasMTT
mod_github_url = https://github.com/ThomasMTT/wandering-traders
enabled_platforms=fabric,forge

# Minecraft properties
minecraft_version=1.20.1
java_version = 17

# Dependencies
fabric_loader_version=0.16.14
fabric_api_version=0.92.6+1.20.1
forge_version=1.20.1-47.4.3
parchment_version=2023.09.03@zip

# For fabric config
yacl_version=3.6.6+1.20.1-fabric