# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Mod Version
mod_version = 0.0.1

# Mod properties
mod_displayname = Wandering Traders
mod_classname = WanderingTraders
mod_description = Discover new wandering traders in Minecraft.\nAlso adds loot recovery (Configurable)
archives_name=wandering-traders
mod_group = life.thoms
mod_id = wandering_traders
mod_license = LGPL-3.0
mod_logo = assets/wandering_traders/icon.png
mod_authors = ThomasMTT
mod_github_url = https://github.com/ThomasMTT/wandering-traders
enabled_platforms=fabric,neoforge

# Minecraft properties
minecraft_version=1.20.6
java_version = 21

# Dependencies
fabric_loader_version=0.16.10
fabric_api_version=0.100.8+1.20.6
neoforge_version=20.6.125
neoforge_simple_version=20
parchment_version=2024.06.16@zip

# For fabric config
yacl_version=3.6.6+1.20.6-fabric
