architectury {
    common rootProject.enabled_platforms.split(',')
}

repositories {
    maven {
        url = "https://maven.parchmentmc.org/"
    }
}

sourceSets.main.java.srcDirs += 'src/gametest/java'
sourceSets.main.resources.srcDirs += 'src/gametest/resources'

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

}