plugins {
    id "com.github.johnrengelman.shadow"
}
architectury {
    platformSetupLoomIde()
    forge()
}


configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    common(project(path: ':common', configuration: 'namedElements')) { transitive = false }
    shadowCommon project(path: ':common', configuration: 'transformProductionNeoForge')
}

processResources {
    filesMatching('META-INF/neoforge.mods.toml') {
        expand mod_id: project.mod_id, displayname: project.mod_displayname, authors: project.mod_authors,
                description: project.mod_description, logo: project.mod_logo, github_url: project.mod_github_url,
                license: project.mod_license, version: project.mod_version, minecraft_version: project.minecraft_version,
                neoforge_simple_version: project.neoforge_simple_version
    }
}

shadowJar {
    exclude "fabric.mod.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    inputFile.set(shadowJar.archiveFile)
    dependsOn shadowJar
    archiveClassifier.set(null)
}

jar {
    archiveClassifier.set("dev")
}

